### ISSUE TITLE
Launch planning

### ISSUE THREAD

**Issue by kytrinyx** [exercism/prolog#1]
_Note: the launch checklist has been made obsolete by a brand new Launch Guide: https://github.com/exercism/docs/blob/master/language-tracks/launch/README.md_

Let's keep the general discussions around what needs to be done here in this issue, and open new, actionable issues for next steps.

**Comment by parkerl** [comment]
I'm in on this one! W00t!

**Comment by kytrinyx** [comment]
@parkerl Yay :-) :tada:

(also, do you see how much better the launch checklist has gotten lately?)

**Comment by parkerl** [comment]
Yes it is fantastic!

**Comment by parkerl** [comment]
@kytrinyx I forget, do you need to setup the Travis integration? When I go there it auto pulls my credentials which is not correct. I was able to turn on the track in Travis.

**Comment by kytrinyx** [comment]
@parkerl yepp, you've got access to do this. Thanks!

**Comment by parkerl** [comment]
I'm wondering if we should use the SWI Prolog logo and SWI Prolog for attribution. Unfortunately, I think the track is vendor specific, and will not work with any other flavor of prolog. I guess that begs the question of renaming the track to reflect this?

**Comment by parkerl** [comment]
Sweet! The SWI Prolog logo is here with many different file types. http://plainicon.com/download-icon/50300/prolog

**Comment by catb0t** [comment]
Something's different about the Prolog track here... where's the JSON object that determines the name that appears, because it should begin with a capital letter.
![lowcase](https://cloud.githubusercontent.com/assets/3238748/20265945/d6fd50ca-aa41-11e6-8e73-65f92c2d7017.png)

**Comment by parkerl** [comment]
@catb0t thanks for catching that. It is here if you want to put in a quick PR https://github.com/exercism/xprolog/blob/master/config.json

**Comment by kytrinyx** [comment]
Yeah, it uses the language key from the config.

**Comment by parkerl** [comment]
@qjd2413 how are you? Wondering if you are still interested in helping launch and maintain this track. We are so close but we just need the final details. Hope you are well.

**Comment by qjd2413** [comment]
Sorry for disappearing! Got distracted by finals week and forgot all about this. Other than documentation, what can I help out with?

**Comment by kytrinyx** [comment]
We need the track image and the documentation. After that we're going to need someone who can check in on the site and participate in the conversations on people's solutions.

**Comment by Anniepoo** [comment]
I'm kinda sorta community manager for SWI-Prolog. The 'Owlie' logo is BSD licensed, but I think I can legitimately give you an okey dokey to use it.

**Comment by kytrinyx** [comment]
@Anniepoo ❤️ That's excellent news. Thank you!

**Comment by Anniepoo** [comment]
Realizing I should be clearer.  We'd be more than happy if you used Owlie as your prolog symbol. If you need a vector artwork version, contact me at anne@swi-prolog.org

**Comment by parkerl** [comment]
@Anniepoo thank you!

**Comment by kytrinyx** [comment]
Quick note. The v2 prototype is in progress http://v2.exercism.io/ and a bunch of things are changing. I updated the original issue here with a link to the new launch guide, which should help it not get so woefully outdated.
