### ISSUE TITLE
Triangle description and tests contradict themselves

### ISSUE THREAD

**Issue by berezovskyi** [exercism/prolog#173]
There is a test in the Triangle problem to check that every equilateral triangle is also an isosceles one. However, the task description explicitly says (emphasis _yours_):

> An _isosceles_ triangle has at least two sides the same length. (It is sometimes specified as having at least two sides the same length, but for the purposes of this exercise we'll say _exactly_ two.)

**Comment by ErikSchierboom** [comment]
Good catch. The tests should indeed reflect the instructions. Would you be willing to submit a PR to update the tests?

**Comment by arnabsen1729** [comment]
The description is now updated to 

> An isosceles triangle has at least two sides the same length. (It is sometimes specified as having exactly two sides the same length, but for the purposes of this exercise we'll say **at least** two.)

So, I guess we can close this issue now.
