### ISSUE TITLE
Queen Attack solution template too empty

### ISSUE THREAD

**Issue by berezovskyi** [exercism/prolog#174]
First of all, thank you so much for putting this course together!

The solution template for the Queen Attack problem is too empty and does not even list the arities of the predicates we are to implement. Also, the purpose and the requirements for the `create/1` predicate are not explained in any way. I simply wrote `create((Dim, Dim)).` in place of that, but I saw some community solutions to limit the board size between 0 and 7.

**Comment by ErikSchierboom** [comment]
Looking into the [stub file](https://github.com/exercism/prolog/blob/main/exercises/practice/queen-attack/queen_attack.pl), it does look like it is less helpful than other stubs (e.g. https://github.com/exercism/prolog/blob/main/exercises/practice/rna-transcription/rna_transcription.pl). Would you be willing to submit a PR to improve this?
