### ISSUE TITLE
Queen Attack has misleading exercise start

### ISSUE THREAD

**Issue by m3m0ry** [exercism/prolog#179]
The exercise start [suggests](https://github.com/exercism/prolog/blob/main/exercises/practice/queen-attack/queen_attack.pl#L12) that the board is from (1,1) to (8,8).

However, the tests seem to think that (0,0) till (7,7) is a [valid](https://github.com/exercism/prolog/blob/main/exercises/practice/queen-attack/queen_attack_tests.plt#L28) chess board.

It should be:
```prolog
% dimensions, e.g. (0,0) or (3,3).
```

**Comment by ErikSchierboom** [comment]
Closed by #180
