### ISSUE TITLE
Consider consistency for the exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/prolog#2]
- Is there a style guide for prolog?
- Are these styles encouraged or enforced?
- Are there any conventions that we should adopt on this track for the sake of consistency?
- Can we enforce these?
- Is there a linter? Are there many? Should we use one?
- Is there a common convention for filenames? If not, what should our convention be?

Note that this is about the exercises (the test suites and code examples), not people's solutions.

**Comment by qjd2413** [comment]
As far as I can tell, Prolog isn't used very often so I can't find any style guides for it. I did, however, find this [linter](http://www.fing.edu.uy/~gbrown/prolog/blint.html), which should hopefully help minimize bugs.

**Comment by kytrinyx** [comment]
Nice, yeah I think it's worth adding a linter to this repo, even if we don't end up recommending one to people who do the exercises.

**Comment by parkerl** [comment]
There is this though a bit dense https://arxiv.org/pdf/0911.2899.pdf

**Comment by qjd2413** [comment]
Just something I noticed when writing the test documentation-- for simplicity, all tests should have the filename `tests.plt` or similar.

**Comment by kytrinyx** [comment]
> for simplicity, all tests should have the filename tests.plt or similar.

That sounds great. In that case, we can change the `config.json` to have that value as a string (no need for a regex).

**Comment by parkerl** [comment]
Cool. I took test_pattern out in the hello-world PR assuming we would have "test" in then name. I will have to update the test file name though.

**Comment by kytrinyx** [comment]
Oh, right. Yeah, we don't actually need the test pattern.

**Comment by parkerl** [comment]
Yeah, I saw that in someone's VERY comprehensive launch checklist! ;-)

**Comment by kytrinyx** [comment]
I wrote it and I _still_ forgot. This is why we have checklists!
