### ISSUE TITLE
Adding a completely new exercice

### ISSUE THREAD

**Issue by marcCanipel** [exercism/prolog#35]
I think, I can add in prolog a new exercice which would be a sudoku.
At the begin you'd have a sudoku's grid and users would need to create a program to solve the sudoku step by step.
And after that, maybe i'll add it to other languages.
I'll post some more info when i've got time.

**Comment by Average-user** [comment]
Maybe you should post that idea directly in [https://github.com/exercism/problem-specifications](https://github.com/exercism/problem-specifications), I think that idea works with languages other than Prolog just as well

**Comment by parkerl** [comment]
@marcCanipel we'd love to see a PR for this.
